### ISSUE TITLE
[Feature request] Added functionality to mark items to delete

### ISSUE THREAD

**Issue by CsBigDataHub** [abrochard/kubel#35]
Ability to mark item to perform actions like delete.

**Comment by abrochard** [comment]
Hey @CsBigDataHub , I just made a feature branch for this. I'm probably going to play around with it for a few days before merging. If you want to check it out and help me out with finding any bugs, I'd appreciate that.

**Comment by CsBigDataHub** [comment]
Sure, @abrochard will do that.

**Comment by abrochard** [comment]
@CsBigDataHub thank you for the feedback! It's very appreciated.

I'm not super familiar with `straight` but it seems that it doesn't properly apply changes. I know that when I define a transient, just evaluating the code isn't enough (like C-x C-e), but rather I have to call `eval-defun` via C-M-x. I am not knowledgeable enough to know the difference or why, but maybe you want to restart Emacs to have a fresh session in doubt?

Anyway, I just pushed some fixes:
1. I think it's the eval problem
2. i'll work on that next
3. it works for me... do you have an error message? it could also be the eval probelm
5. that was a real bug that I just fixed by renaming function

**Comment by CsBigDataHub** [comment]
@abrochard ,

Figured out the issue here.

> 1. I think it's the eval problem

I have been using `kubel-evil` and the `kubel-evil-help-popup` in not updated with latest changes.

2. Is working now.
3. This is still now working with `kubel-evil`.
> 5. that was a real bug that I just fixed by renaming function

This is working now.

**Comment by abrochard** [comment]
Ah good find! I always forget about `kubel-evil` since I don't use it. Gonna take a pass at it.

**Comment by abrochard** [comment]
Ok just pushed something for kubel-evil. Not sure what I'm doing.

**Comment by CsBigDataHub** [comment]
Everything looks good.

These evil-keybindings can be updated with this code below so that it is consistent with `kubel.el`

https://github.com/abrochard/kubel/blob/4e863a0d5b59acddf62c976da5c26be887a72aff/kubel-evil.el#L92

```emacs-lisp
(evil-define-key 'motion kubel-evil-mode-map
  (kbd "RET") #'kubel-get-resource-details
  (kbd "K") #'kubel-set-kubectl-config-file
  (kbd "C") #'kubel-set-context
  (kbd "n") #'kubel-set-namespace
  (kbd "g") #'kubel
  (kbd "h") #'kubel-help-popup
  (kbd "?") #'kubel-help-popup
  (kbd "F") #'kubel-set-output-format
  (kbd "R") #'kubel-set-resource
  (kbd "k") #'kubel-delete-popup
  (kbd "f") #'kubel-set-filter
  (kbd "r") #'kubel-rollout-history
  (kbd "E") #'kubel-quick-edit
  (kbd "M-n") #'kubel-jump-to-next-highlight
  (kbd "M-p") #'kubel-jump-to-previous-highlight
  (kbd "$") #'kubel-show-process-buffer
  (kbd "p") #'kubel-port-forward-pod
  (kbd "l") #'kubel-log-popup
  (kbd "c") #'kubel-copy-popup
  (kbd "e") #'kubel-exec-popup
  (kbd "j") #'kubel-jab-deployment
  (kbd "u") #'kubel-unmark-item
  (kbd "M") #'kubel-mark-all
  (kbd "U") #'kubel-unmark-all)
```

**Comment by abrochard** [comment]
Thanks for the code sample! I modified it since I don't think you want `j` and `k` bound to kubel functions, and pushed just now. Working on README in the meantime.
