### ISSUE TITLE
[Bug?] kubel-use-namespace-list auto doesn't work

### ISSUE THREAD

**Issue by snowiow** [abrochard/kubel#53]
I'm not sure if this is really a bug or not, but if I execute the command from the code to determine if I'm able to list namespaces I get the following warning before the real answer:

```
 $ kubectl auth can-i list namespaces -n default
Warning: resource 'namespaces' is not namespace scoped
yes
```

Sadly I can't find anything online regarding this specific warning and if I'm the only one having this problem. But would it make sense to check if a line with yes exists instead of checking the whole output for equality? https://github.com/abrochard/kubel/blob/master/kubel.el#L703

If this change is welcome, I would like to try to implement a fix myself, since it's quite some time since I last contributed 😄

**Comment by abrochard** [comment]
Hi @snowiow !
Yeah this was discussed in #38 and there's #44 currently open on the topic. It's currently unclear to me what is the best course of action because the `can-i`  command cannot be trusted and there are so many possible edge cases here based on cluster configurations.
The current system is to have `kubel-use-namespace-list` default to a fairly  conservative `auto` behavior such that we reduce the risk of kubel appearing completely broken for new users if they have an edge case. Meanwhile advanced users can explore with the `on` or `off` option.
If there is a better solution out there, I'm very interested.

**Comment by snowiow** [comment]
ah thank you, didn't see the older issue and the PR. Sadly I also don't know of a better solution.
I'll go with `(setq kubel-use-namespace-list 'on)` for now 👍
